[[main]]
  name = "Team"
  url = "/#team"
  weight = 1

[[main]]
  name = "Projects"
  url = "/#projects"
  weight = 2

[[main]]
  name = "Values"
  url = "/#values"
  weight = 3

[[main]]
  name = "Vote"
  url = "/#vote"
  weight = 4

[[social]]
  name = "Github"
  url = "https://github.com/teloskitchen"
  weight = 1
  [social.params]
    icon = "icons/github.fix.me.svg"

[[social]]
  name = "Twitter"
  url = "https://twitter.com/TelosKitchen"
  weight = 2
  [social.params]
    icon = "icons/twitter.svg"

[[social]]
  name = "Gitlab"
  url = "https://gitlab.com/telos-kitchen"
  weight = 3
  [social.params]
    icon = "icons/gitlab.svg"