title = 'Telos Kitchen'
titleSeparator = "|"
description = "We are a global team focused on block production and innovation on Telos. We operate on bare metal servers located in New York City."
thumbnail = "logo/logo.png"